# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 00:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Скликання')),
                ('year_from', models.IntegerField(blank=True, null=True, verbose_name='З')),
                ('year_to', models.IntegerField(blank=True, null=True, verbose_name='По')),
            ],
            options={
                'verbose_name': 'Скликання',
                'verbose_name_plural': 'Скликання',
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Регіон')),
                ('slug', models.CharField(max_length=20, verbose_name='slug')),
                ('koatuu', models.CharField(blank=True, max_length=20, verbose_name='КОАТУУ')),
            ],
            options={
                'verbose_name': 'Регіон',
                'verbose_name_plural': 'Регіони',
            },
        ),
        migrations.CreateModel(
            name='MemberOfParliament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='ПІБ')),
                ('link', models.URLField(blank=True, max_length=512, verbose_name='Посилання')),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('img_retrieved', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Депутат',
                'verbose_name_plural': 'Депутати',
            },
        ),
        migrations.CreateModel(
            name='Minion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='ПІБ')),
            ],
            options={
                'verbose_name': 'Помічник',
                'verbose_name_plural': 'Помічники',
            },
        ),
        migrations.CreateModel(
            name='Minion2MP2Convocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.CharField(max_length=200, verbose_name='Підтверджено')),
                ('minion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Minion')),
            ],
            options={
                'verbose_name': 'Належність помічника до депутата',
                'verbose_name_plural': 'Належності помічників до депутатов',
            },
        ),
        migrations.CreateModel(
            name='MP2Convocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.CharField(blank=True, max_length=200, verbose_name='Партія')),
                ('fraction', models.CharField(blank=True, max_length=200, verbose_name='Фракція')),
                ('comission', models.CharField(blank=True, max_length=200, verbose_name='Комісія')),
                ('link', models.URLField(blank=True, max_length=512, verbose_name='Посилання')),
                ('convocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Convocation')),
                ('mp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MemberOfParliament')),
            ],
            options={
                'verbose_name': 'Належність до скликання',
                'verbose_name_plural': 'Належності до скликання',
            },
        ),
        migrations.CreateModel(
            name='PublicOffice',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Рада')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.County')),
            ],
            options={
                'verbose_name': 'Орган влади',
                'verbose_name_plural': 'Органи влади',
            },
        ),
        migrations.AddField(
            model_name='minion2mp2convocation',
            name='mp2convocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MP2Convocation'),
        ),
        migrations.AddField(
            model_name='minion',
            name='mp',
            field=models.ManyToManyField(through='core.Minion2MP2Convocation', to='core.MP2Convocation', verbose_name='Депутат'),
        ),
        migrations.AddField(
            model_name='memberofparliament',
            name='convocations',
            field=models.ManyToManyField(through='core.MP2Convocation', to='core.Convocation', verbose_name='Скликання'),
        ),
        migrations.AddField(
            model_name='convocation',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PublicOffice'),
        ),
    ]
