# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicoffice',
            name='kind',
            field=models.IntegerField(choices=[(0, 'Обласна рада'), (1, 'Міська рада')], default=0, verbose_name='Тип органу'),
        ),
    ]
