# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_publicoffice_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mp2convocation',
            name='comission',
            field=models.CharField(blank=True, max_length=512, verbose_name='Комісія'),
        ),
        migrations.AlterField(
            model_name='mp2convocation',
            name='fraction',
            field=models.CharField(blank=True, max_length=512, verbose_name='Фракція'),
        ),
        migrations.AlterField(
            model_name='mp2convocation',
            name='party',
            field=models.CharField(blank=True, max_length=512, verbose_name='Партія'),
        ),
    ]
