# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170825_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberofparliament',
            name='img_retrieved',
        ),
        migrations.RemoveField(
            model_name='memberofparliament',
            name='link',
        ),
    ]
